# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-25 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('url_imagen', models.ImageField(default='default.png', upload_to='')),
                ('likes', models.CharField(blank=True, default='0', max_length=100)),
                ('Descripción', models.TextField()),
            ],
        ),
    ]
